### ISSUE TITLE
tapdaq is breaking androidmanifest.xml

### ISSUE THREAD

**Issue by ayublin** [tapdaq/unity-plugin#37]
Hello,

Upon installing tapdaq unity SDK, we noticed that our manifest being abruptly changed and causes several other plugins we're using to break.

Can you please provide an instruction on what changes needed to be made on AndroidManifest.xml so that we can carefully done that ourself?

Thanks.

**Comment by nickreffitt** [comment]
Hi @ayublin 

I'm sorry you are having issues when building out to Android, we are currently in the process of reducing the number of entries in the AndroidManifest.xml file, so that we prevent conflicts from happening. I will keep you posted on when we push live this update.

You can view out entries into the AndroidManifest.xml file by visiting our [Android Quickstart](https://tapdaq.com/docs/tapdaq-android-sdk/Quickstart) 

Out of interest, what plugins are you using?

All the best

Nick

**Comment by ayublin** [comment]
So after doing a test import of tapdaq unity plugin on a fresh project, it turns out that tapdaq plugin include an androidmanifest.xml file, which will overwrite the project manifest, check this out:

![image](https://cloud.githubusercontent.com/assets/1355215/23101416/98ac4a08-f6c5-11e6-9001-c1b7c898db45.png)

I think that's a really bad practice as people could miss it and got their own manifest fully overwritten, which is what happened to us and broke some of our features (we have reverted it via git now).

My experience with plugins/SDK that needs to modify android manifest will have a mechanism where it automatically add or change the manifest via scripting, or a proper manual instruction would be fine.

Also the manifest by tapdaq changes the default activity to this:

```
<activity android:name="com.nerd.TapdaqUnityPlugin.TapdaqUnity" android:label="@string/app_name" android:screenOrientation="sensorPortrait" android:launchMode="singleTask" android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
    </activity>
```

Is this required to get tapdaq working on unity? As for plugins, we're using fabric, facebook and another plugin from unity asset store.

Thanks!

**Comment by nickreffitt** [comment]
Hi @ayublin 

Thanks for this, it's really useful, and I appreciate you taking the time out to put this together for us.

This week we're focusing our efforts on the following:
A) Reducing the number of entries in the AndroidManifest.xml
B) Reviewing our folder structure in the Unity plugin to prevent conflicts with other plugins

We're also testing out several full-game unity applications as part of our QA so that we can highlight any potential conflicts with the manifest in our docs. 

I will keep you posted on our progress.

All the best

Nick

**Comment by ayublin** [comment]
That's a solid plan 👍  Thanks for responding and taking action upon this very quickly.

**Comment by rdominic** [comment]
Hi @ayublin 

The <activity android:name="com.nerd.TapdaqUnityPlugin.TapdaqUnity"> activity is vital, it replaces/extends the regular UnityPlayerActivity.

You can see everything we add to the manifest in the sample project manifest, you should add all the activities for the networks that you require, if they're not added, the networks will not be available, logs will print in the console when they try to be used and they will appear red in the debugger.

For permissions, you'll need these:
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

The external storage permissions are optional but recommended.

Here's the sample project manifest:
https://github.com/tapdaq/unity-plugin/blob/master/Samples/MediationSample/Assets/Plugins/Android/AndroidManifest.xml

As Nicks said, we're reviewing this and on top of what he's said, we'll also produce a manual integration document for the manifest.

Thanks for your continued feedback.
Dominic

**Comment by nickreffitt** [comment]
Hi @ayublin 

We have recently updated our Unity Quickstart guide to explain how to resolve manifest conflicts.

You can view the specific section on this here: https://tapdaq.com/docs/unity-plugin/Quickstart#6-android-specific-steps

Let me know if this helps resolve your issue.

All the best

Nick

**Comment by ayublin** [comment]
Thanks those are very helpful!
