### ISSUE TITLE
Close on Launch

### ISSUE THREAD

**Issue by Entity3Ltd** [tapdaq/unity-plugin#49]
Getting a crash / close on launch on iOS / Xcode

Xcode gives following message

dyld: Library not loaded: @rpath/AdMobAdapter.framework/AdMobAdapter

dyld`__abort_with_payload:
    0x102c15cb4 <+0>:  movz   x16, #0x209
    0x102c15cb8 <+4>:  svc    #0x80
->  0x102c15cbc <+8>:  b.lo   0x102c15cd4               ; <+32>
    0x102c15cc0 <+12>: stp    x29, x30, [sp, #-16]!
    0x102c15cc4 <+16>: mov    x29, sp
    0x102c15cc8 <+20>: bl     0x102c15500               ; cerror_nocancel
    0x102c15ccc <+24>: mov    sp, x29
    0x102c15cd0 <+28>: ldp    x29, x30, [sp], #16
    0x102c15cd4 <+32>: ret

**Comment by Entity3Ltd** [comment]
Seems like I had to add the '.framework' files into the 'Embedded Binaries' section of Xcode for this to launch without crashing.

Is the what you would expect as I did not see this mentioned in the Wiki?

Thanks

**Comment by rdominic** [comment]
There's a known issue with the Unity Editor not running our script correctly that we're trying to work around, however we're aware that iOS frameworks don't always get added as Embedded Binaries in XCode, to ensure they do, when you switch to iOS platform, you should select the UnityEditor window which will trigger the script (that should run when you switch to iOS).

https://github.com/tapdaq/unity-plugin/wiki/Quickstart#c-known-issues

We also recommend "replacing" rather than "Appending" xcode projects, as this can add the binaries twice.

**Comment by Entity3Ltd** [comment]
My build is on iOS and i do not need to switch between builds. In this case is there a way to force the script to run?

This isnt an issue as I will just manually add them for now. This can probably be closed but I look forward to the future update with a fix

**Comment by rdominic** [comment]
Yes, there is a "Run iOS Build PostProcess" button in the Tapdaq menu which will also do this.

You can tell that its successful before building your iOS project, the ad network frameworks should be in the embedded frameworks section 
![screen shot 2017-03-31 at 17 00 36](https://cloud.githubusercontent.com/assets/5871110/24558615/b00983c2-1633-11e7-95b0-c7520133a41d.png)
