### ISSUE TITLE
Cached video not validated?

### ISSUE THREAD

**Issue by asancio** [tapdaq/unity-plugin#52]
Hello, 
if while playing the player get disconnected from internet, tapdaq still show video ads (i think the videos get loaded from the cache), the problem is that after the player watch these videos, the OnRewardVideoValidated don't get called. So our players watch the videos but don't get any reward or gift.

We are using Tapdaq 4.2.1
Unity 5.5.2 p4, Android

**Comment by nickreffitt** [comment]
Hey @asancio 

Thanks for reporting this, it's an interesting problem, because we invoke the didLoad.. calback for the relevant ad, and the user could go offline. I'll add this to our roadmap and see what we can come up with.

Feel free to reach out to us on support@tapdaq.com if you have any more feedback, it's really useful!

All the best,

Nick
